apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

images:
- name: gcr.io/heptio-images/ks-guestbook-demo
  newTag: "0.1"

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
